Repository Sokom141/BattleShip, pull requests merged in 2020-11, with the labels that each got.

#25 color selection added and bug fixes
  src/main/java/com/battleship/gui/GameBoard.java
  src/main/java/com/battleship/gui/Settings.form
  src/main/java/com/battleship/gui/Settings.java
  src/main/java/com/battleship/gui/ShipPlanner.java
  src/main/java/com/battleship/utils/BSConfigFile.java
Labels: bug, enhancement

#26 enhancement for issue #19 and addition of some mnemonics for Window
  src/main/java/com/battleship/gui/Window.form
  src/main/java/com/battleship/gui/Window.java
  src/main/resources/images/anonymous.png
  src/main/resources/images/avatar.png
  src/main/resources/images/link.png
  src/main/resources/images/logout.png
  src/main/resources/images/server.png
  src/main/resources/images/settings.png
  src/main/resources/images/ship.png
  src/main/resources/properties/version.properties
Labels: enhancement, good first issue

#29 Enhancement 10 resolution
  src/main/java/com/battleship/gui/GameBoard.java
Labels: enhancement

#30 Added the first version of CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement, good first issue

#37 Update ShipPlanner.java
  src/main/java/com/battleship/gui/ShipPlanner.java
Labels: bug, good first issue

#33 Codeql CWE 502
  src/main/java/com/battleship/gui/GameBoard.form
  src/main/java/com/battleship/gui/GameBoard.java
  src/main/java/com/battleship/gui/Window.java
  src/main/java/com/battleship/networking/LookAheadObjectInputStream.java
  src/main/java/com/battleship/networking/NetworkConnection.java
Labels: bug, enhancement

#38 JUnit 5 support
  pom.xml
  src/main/java/com/battleship/gui/ShipPlanner.java
  src/test/java/com/battleship/networking/LookAheadObjectInputStreamTest.java
Labels: enhancement
